# Form implementation generated from reading ui file '.\templates\dlgAbout.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlgAbout(object):
    def setupUi(self, dlgAbout):
        dlgAbout.setObjectName("dlgAbout")
        dlgAbout.resize(500, 400)
        dlgAbout.setModal(True)
        self.image = QtWidgets.QLabel(parent=dlgAbout)
        self.image.setGeometry(QtCore.QRect(120, 10, 251, 241))
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap(".\\templates\\../img/omega.png"))
        self.image.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.image.setWordWrap(False)
        self.image.setObjectName("image")
        self.lbltext = QtWidgets.QLabel(parent=dlgAbout)
        self.lbltext.setGeometry(QtCore.QRect(170, 320, 161, 31))
        self.lbltext.setObjectName("lbltext")
        self.label = QtWidgets.QLabel(parent=dlgAbout)
        self.label.setGeometry(QtCore.QRect(160, 260, 181, 41))
        self.label.setObjectName("label")
        self.btnCloseabout = QtWidgets.QPushButton(parent=dlgAbout)
        self.btnCloseabout.setGeometry(QtCore.QRect(210, 350, 80, 25))
        self.btnCloseabout.setMinimumSize(QtCore.QSize(80, 25))
        self.btnCloseabout.setSizeIncrement(QtCore.QSize(80, 25))
        self.btnCloseabout.setObjectName("btnCloseabout")

        self.retranslateUi(dlgAbout)
        QtCore.QMetaObject.connectSlotsByName(dlgAbout)

    def retranslateUi(self, dlgAbout):
        _translate = QtCore.QCoreApplication.translate
        dlgAbout.setWindowTitle(_translate("dlgAbout", "Dialog"))
        self.lbltext.setText(_translate("dlgAbout", "Text"))
        self.label.setText(_translate("dlgAbout", "Copyright"))
        self.btnCloseabout.setText(_translate("dlgAbout", "Close"))
